### ISSUE TITLE
AMI Workflow Enhancements for 0.5.0

### ISSUE THREAD

**Issue by alliomeria** [esmero/ami#37]
# What is needed?

Options that enable users to:

- [x] Define an AMI set label when initially creating a set 
      - instead of having to Edit this after the set is created
- [ ] Define ownership of digital objects and collections created from an AMI set
      - autocomplete search against existing user IDs? 
      - defaults as checkbox for option such as "default ownership same as AMI set creator"?
- [ ] Determine the separator/delimeter used for certain multiple-value elements 
      - main AMI default separator/delimiter set to semicolon `;` for Files
      -  I7 Solr Importer plugin uses `|@|` for multiple-value elements
- [ ] For I7 Solr Importer, option to deselect fetched columns/keys/elements 
      - potentially as an additional step after initial configuration choices
- [x] #69 
- [ ] #70 

**Related separate issue discussions/issues:** 
- [x] 🌟 https://github.com/esmero/ami/issues/8
- [x] See all of the Processed ADOs associated with an AMI Set in a list/tab
- [ ] When working in the 'Edit Reconciled LoD' tab of your Ami Set, have an option to Filter by Checked/Unchecked (*from [Issue #69](https://github.com/esmero/ami/issues/69))*
- [ ] In the Processed LoD CSV, include a Notes column to include information about the AMI Set origination and date (*from [Issue #69](https://github.com/esmero/ami/issues/69))*
- [ ] Alphabetic sorting of CSV Header Columns on LoD Reconcile form during configuration #148  

@DiegoPino @aksm @karomabiles anything else that should be part of this issue?

**Comment by alliomeria** [comment]
🚀 Progress Update:
1. Define an AMI set label ✅ - Part of [work being done on pull/31](https://github.com/esmero/ami/pull/31/commits/a1619396fc599ea24d0b45f052c4deead2e2627b)

This is great to have at the time of set creation @DiegoPino!

**Comment by karomabiles** [comment]
@alliomeria
- Create a log report/view of sorts that can track/show ingest alerts/history per AMI set

**Comment by alliomeria** [comment]
Hello @karomabiles & @dmer, added a star to the related issue above for the "Add a Report Tab to each AMI Set" issue. :nerd_face: This will be a great feature!
